data:
  batch_size: 224
  num_workers: 1
  pin_mem: true
logging:
  folder: log/vith14.224-bs.2048-ep.300/
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
meta:
  copy_data: false
  load_checkpoint: false
  model_name: gene_base
  pred_depth: 3
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: false
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 300
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04
