"""
Adapted from Assran, M. et al. Self-supervised learning from images with a
Joint-Embedding Predictive Architecture. Proc. IEEE Comput. Soc. Conf. Comput.
Vis. Pattern Recognit. 15619–15629 (2023);
https://github.com/facebookresearch/ijepa/blob/main/src/utils/tensors.py
(05.06.2024).
"""

import math

import numpy as np
import torch


def get_1d_sincos_pos_embed(embed_dim: int,
                            n_zero_pos: int,
                            n_sincos_pos: int,
                            ) -> np.ndarray:
    """
    Retrieve 1D sin cos positional embedding.

    Parameters
    -----------
    embed_dim:
        Output dimension of the positional embedding (for each position). Has to
        be divisible by 2.
    n_zero_pos:
        Number of positions to be embedded with 0s.
    n_sincos_pos:
        Number of positions to be embedded with sin cos positional embeddings.

    Returns
    -----------
    pos_embed:
        The positional embedding with shape (n_zero_pos+n_sincos_pos,
        embed_dim).
    """
    sincos_pos = np.arange(n_sincos_pos, dtype=float)
    pos_embed = _get_1d_sincos_pos_embed_from_pos(embed_dim, sincos_pos)
    if n_zero_pos > 0:
        pos_embed = np.concatenate(
            [np.zeros([n_zero_pos, embed_dim]), pos_embed],
            axis=0)

    return pos_embed


def drop_path(x: torch.Tensor,
              drop_prob: float=0.0,
              training: bool=False,
              ) -> torch.Tensor:
    """
    Helper function for forward pass of DropPath module.

    Parameters
    -----------
    x:
        Input to DropPath module forward pass.
    drop_prob:
        Probability for dropping paths.
    training:
        If 'True', do not drop paths.

    Returns
    -----------
    output:
        Output of DropPath module forward pass, with some paths dropped (set to
        0) and others scaled.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    
    # Create binary random tensor
    shape = (x.shape[0],) + (1,) * (x.ndim - 1) # works with tensors of diff dim
    random_tensor = keep_prob + torch.rand(shape,
                                           dtype=x.dtype,
                                           device=x.device)
    random_tensor.floor_()

    # Drop some paths by setting them to 0 and scale rest to keep sum consistent
    output = x.div(keep_prob) * random_tensor

    return output


def repeat_interleave_batch(x, B, repeat):
    N = len(x) // B
    x = torch.cat(
            [torch.cat([x[i*B:(i+1)*B] for _ in range(repeat)], dim=0)
             for i in range(N)],
            dim=0)

    return x


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def _get_1d_sincos_pos_embed_from_pos(embed_dim: int,
                                     pos: np.ndarray,
                                     ) -> np.ndarray:
    """
    Retrieve 1D sin cos positional embedding from an array of positions/sequence
    index.

    Parameters
    -----------
    embed_dim:
        Output dimension of the positional embedding (for each position). Has
        to be divisible by 2.
    pos:
        An array containing the positions to be embedded.
        
    Returns
    -----------
    pos_emb:
        The positional embedding with shape (len(pos), embed_dim).
    """
    assert embed_dim % 2 == 0
    omega = np.arange(embed_dim // 2, dtype=float)
    omega /= embed_dim / 2.
    omega = 1. / 10000**omega # shape (EMBED_DIM/2,)

    pos = pos.reshape(-1) # shape (SEQ_LEN,)
    out = np.einsum('m,d->md', pos, omega) # shape (SEQ_LEN, EMBED_DIM/2);
                                           # outer product

    emb_sin = np.sin(out) # shape (SEQ_LEN, EMBED_DIM/2)
    emb_cos = np.cos(out) # shape (SEQ_LEN, EMBED_DIM/2)

    pos_emb = np.concatenate([emb_sin, emb_cos], axis=1) # shape (SEQ_LEN,
                                                         # EMBED_DIM)

    return pos_emb


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    """
    Cut & paste from PyTorch official master until it's in a few official
    releases - RW Method based on
    https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    """
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor