# All keys in this YAML file must be in capital letters since
# they will be treated as environmental variables.

job_requirement:
  LSB_DEFAULT_USERGROUP: team361  # The user group to be used for scheduling the job.
  QUEUE: "gpu-parallel"  # The job queue to be used for scheduling the job.
  NUM_NODES: 1  # Number of compute nodes required for the job.
  NUM_GPUS_NODE: 8  # Number of GPUs per node.
  NUM_PROCESSES_NODE: 128  # Number of processes per node.
  MEM_NODE: 896  # Memory allocated per node (in GB).
  
infiniband:
  NCCL_IB_DISABLE: 1  # 1: Disable InfiniBand, 0: Enable InfiniBand

environment:
  ENV_PATH: "/nfs/users/nfs_s/sb75/.venvs/nichejepa"  # Path to the environment to be activated.

artifact:
  ARTIFACT_LOCATION: "/lustre/scratch126/cellgen/lotfollahi/sb75/nichejepa-reproducibility/artifacts/hst_corpus_80m"  # Path to store the artifacts.
  EXPERIMENT_NAME: "nichejepa_pretraining"  # Name of the experiment.
  RUN_NAME: "hst_corpus_80m_gtsmall_nosampling_samplesegments_09995ema-1"  # Name of the run.

runner_script:
  RUNNER_SCRIPT: "/nfs/team361/sb75/nichejepa/src/app/runner.sh"  # Path to the runner script.
  TRAINING_SCRIPT_PATH: "/nfs/team361/sb75/nichejepa/src/app/main_dist.py"  # Path to the training script.
  BACKEND: "nccl"  # Backend for distributed training.
  CONFIG_FILE: "/nfs/team361/sb75/nichejepa/configs/model/hst_corpus_80m/hst_corpus_80m_gtsmall_nosampling_samplesegments_09995ema.yaml"
