data:
  batch_size: 30
  seq_len: 2781
  #seq_len: 1302
  #vocab_size: 1356
  #vocab_size: 6033 
  vocab_size: 2781
  #vocab_size: 1304
  num_workers: 12
  pin_mem: true
  #data_path: /lustre/scratch126/cellgen/team361/mv10/jepa/nichejepa/simulated_hrd.dataset
  #data_path: /lustre/scratch126/cellgen/team361/mv10/jepa/nichejepa/simulated.dataset
  #data_path: /lustre/scratch126/cellgen/team361/mv10/jepa/nichejepa/cell_neighborhood_tokenizer.dataset
  data_path: /lustre/scratch126/cellgen/team361/mv10/jepa/nichejepa/scGPT.dataset  
  #data_path: /lustre/scratch126/cellgen/team361/mv10/jepa/nichejepa/sim_hard_total.dataset 
  split: 0.6
  Total_seed: 1
logging:
  #folder: logs/sim_hard_ema0.8_100_200_40_1_1_seed
  #save_folder: out_put/sim_data_hard/cell_neighborhood_token
  #folder: logs/sim_ema0.8_100_200_40_1_1_seed
  #save_folder: out_put/sim_data_top256/cell_neighborhood_token      
  #folder: logs/nanostring_ema0.8_100_200_40_1_1_seed
  #save_folder: out_put/nanostringtop256/cell_neighborhood_token  
  #folder: logs/sim_hard_total_ema0.9_target30_context300_epoch100_encoder6_target3_ntargets4_pred_emb_dim_384_split0.2_seed
  #save_folder: out_put/scGPTtop30/sim_hard_total_ema0.8_target30_context300_epoch30_enc6_pred3_seed
  folder: logs/scGPT_ema0.8_target20_context134_epoch10_encoder2_target1_emb384_numtarget4_numcon1_learn_split0.6_benchmark_seed
  save_folder: out_put/scgpt/0.6_percent_test
  #save_folder: out_put/scgpt/AQP4_2040
  #folder: logs/scGPT_ema0.8_target20_context2700_epoch4_encoder2_target1_split0.2_seed
  #save_folder: out_put/scGPTtop30/AQP4_2040
  write_tag: jepa
mask:
  n_targets: 1
  n_contexts: 1
  target_mask_size: 20
  context_mask_size: 2700
  top_niche: -1
  top_cell_type: 2781 

meta:
  copy_data: false
  load_checkpoint: true
  model_name: gt_base
  pred_depth: 1
  pred_emb_dim: 384
  enc_depth : 2
  enc_emb_dim : 384
  read_checkpoint: null
  use_bfloat16: false
optimization:
  ema:
  - 0.8
  - 1.0
  epochs: 100
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04