data:
  batch_size: 10
  data_path: /lustre/scratch126/cellgen/team361/mv10/nichejepa-reproducibility/nichejepa-reproducibility/datasets/st_data/gold/cell_neighborhood_tokenizer/sim1_1105fts_10000locs/sim1_1105fts_10000locs_read_depth_shifted_log_2210.dataset
  data_set_name: 'Simulated_data'
  num_workers: 18
  pin_mem: true
  vocab_size: 1107
  incl_cell_seq: True
  incl_neighborhood_seq: True
  seq_len_cell: 361
  seq_len_neighborhood: 1091
  has_cls: True
  sample_size: 100000
  sample_subset: False
  random_state: 0
  stratify: False
  split: 0.2
  specific_cell_types: []
  #specific_cell_types: ['Celltype5','Celltype6']
emb:
  weighted_average: False
  average: True
  cls: False
  select_topk: False
  retrieve_gene: False
  retrieve_niche: False
  retrieve_cell: True
  gene_id: 332
  retrieve_position_emb: False
  retrieve_emb_from_layer: 2 # This indicates that we should retrieve embeddings from the layer specified by #retrieve_emb_from_layer and upwards its value should be between zero and #enc_depth-1
logging:
  folder: logs/merfish_200
  write_tag: jepa
mask:
  context_mask_size: 361
  target_mask_size: 19
  n_contexts: 1
  n_targets: 4

meta:
  copy_data: false
  enc_depth: 3
  load_checkpoint: false
  model_name: gt_base
  pred_depth: 1
  pred_emb_dim: 768
  enc_emb_dim: 768
  enc_pred_depth: 31
  top_k: 127
  read_checkpoint: null
  use_bfloat16: True
optimization:
  ema:
  - 0.999
  - 1.0
  learnable: 1
  epochs: 15
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.000001
  start_lr: 5.0e-05
  warmup: 5
  weight_decay: 0.04