data:
  dataset_name: 'xhs1000-39b_1p'
  raw_data_folder_path: '/lustre/scratch126/cellgen/lotfollahi/DATASETS/silver/xhs1000-39b_1p'
  token_dict_folder_path: '/lustre/scratch126/cellgen/lotfollahi/DATASETS/tokenizer/token_dictionary_homo_sapiens.pkl'
  tokenized_data_folder_path: '/lustre/scratch126/cellgen/lotfollahi/DATASETS/gold/cell-graph-tokenizer/xhs1000-39b_1p/xhs1000-39b_1p_32_None_None_None_None_None_shifted_log_knn_10_2816.dataset'
  precomputed_split: null
  precomputed_n_nonzero_tokens: null
  test_batch_ids: ['49_batch0']
  val_batch_ids: ['49_batch0']
  tokenizer_type: 'cell_graph'
  random_state: 0
  sample_subset: False
  split: 0
  stratify: False
  seq_len_cell: 256 # 64, 128, 256
  seq_len_neighborhood: 2560 # 384/640, 1536/2816
  n_segments: 11 # 7, 11; number of unique segment tokens (gene segments)
  sampling_strategy: null # null, 'rand_sampling', 'norm_count_rank_sampling', 'rand_sampling_rep', 'norm_count_rank_sampling_rep'
  batch_size: 224 # 224, 256, 128, 288
  num_workers: 16
  pin_memory: True
  sep_gene_tokens_neb: False
  use_sampler: True
  n_special_values: 1000
  nz_spc: True
  overwrite_batch_value: False
  mega_batch_mult_max: 10000
meta:
  api_version: 'v3'
  add_cls: False
  n_cls: 1
  gt_type: 'combined' # 'rank', 'counts', 'combined'
  count_encoding: 'mlp' # 'value_bins', 'mlp'
  n_value_bins: 20
  cell_pos_enc: 'segment' # 'segment', 'coord'
  enc_depth: 12
  enc_emb_dim: 384 # 384, 768
  pred_depth: 12 # 12
  pred_emb_dim: 192 # 384, 192, 384
  num_heads: 6 # 12, 6
  mlp_ratio: 4
  special_tokens: ['batch'] # ['batch'], ['assay', 'batch'],['assay', 'gene_panel', 'batch'], ['tissue', 'assay', 'gene_panel', 'batch']
  pos_learnable: False
  seg_learnable: False
  use_bfloat16: True
  use_flash_attention: True
  use_layer_norm: True
  predict_gene: True
  new_spc: True
  restrict_special_attention: False
  excl_spc_from_loss: False
  target_enc_layer_norm: False
mask:
  n_contexts: 1 # 1
  n_targets: 1 # 5 # 1 =, this is the number of blocks in block masking
  block_masking: True # True, False
  cell_masking: False # True, False
  targets_list: null
  context_mask_size: 200 # this doesn't have meaning in block masking.
  target_mask_size: 50 # this doesn't have meaning in block masking.
  per_block_mask_ratio: 0.6 # 0.2, 0.4, 0.6, 0.8
  sample_segments: True
  special_token_pad_ratio: 0.0
optimization:
  warmup: 3 # 1
  epochs: 100 # 5
  ema:
  - 0.9995 # 0.998, 0.9995
  - 1.0
  start_lr: 2.0e-05 # 1.0e-06, 2.0e-05
  lr: 6.0e-05 # 6.0e-05, 0.000625
  final_lr: 2.0e-05 # 1.0e-06
  weight_decay: 0.04 # 0.04
  final_weight_decay: 0.4 # 0.4
  ipe_scale: 1.25
  clip_grad: 2.0
  lambda_var: 0.
  lambda_cov: 0.
state:
  log_freq: 20
  checkpoint_freq: 5
  write_tag: nichejepa
  read_timestamp: ''
  folder_path: null
  load_checkpoint: False # true, false
  read_checkpoint: null # null, 'nichejepa-ep5.pth.tar'
  checkpoint_freq_iter: 5000