# All keys in this YAML file must be in capital letters since
# they will be treated as environmental variables.

job_requirement:
  LSB_DEFAULT_USERGROUP: team361  # The user group to be used for scheduling the job.
  QUEUE: "training-parallel"  # The job queue to be used for scheduling the job.
  NUM_NODES: 1  # Number of compute nodes required for the job.
  NUM_GPUS_NODE: 8  # 8 Number of GPUs per node.
  NUM_PROCESSES_NODE: 64  # 64 Number of processes per node.
  MEM_NODE: 64  # 64 Memory allocated per node (in GB).

infiniband:
  NCCL_IB_DISABLE: 1  # 1: Disable InfiniBand, 0: Enable InfiniBand

environment:
  ENV_PATH: "/nfs/users/nfs_s/sb75/.venvs/nichejepa"  # Path to the environment to be activated.

artifact:
  ARTIFACT_LOCATION: "/nfs/team361/sb75/nichejepa-reproducibility/artifacts/mmb0-1b_smb1-1b_2p"  # Path to store the artifacts.
  WAREHOUSE_PATH: "/nfs/team361/sb75/nichejepa-reproducibility/artifacts/mmb0-1b_smb1-1b_2p"  # Path to store the artifacts.
  OUTPUT_DIR: "/nfs/team361/sb75/nichejepa-reproducibility/artifacts/mmb0-1b_smb1-1b_2p"  # Path to store the artifacts.
  LOG_DIR: "/nfs/team361/sb75/nichejepa-reproducibility/artifacts/mmb0-1b_smb1-1b_2p"
  EXPERIMENT_NAME: "terra_mmb0-1b_smb1-1b_2p"  # Name of the experiment.
  RUN_NAME: "run324_cell_neigh_tokenizer_rank_900ep"  # Name of the run.

runner_script:
  RUNNER_SCRIPT: "/nfs/team361/sb75/nichejepa/src/app/training/train_model_lsf_mpirun_sanger.sh"  # Path to the runnaazazer script.
  TRAINING_SCRIPT_PATH: "/nfs/team361/sb75/nichejepa/src/app/training/main.py"  # Path to the training script.
  BACKEND: "nccl"  # Backend for distributed training.
  CONFIG_FILE: "/nfs/team361/sb75/nichejepa/configs/model/mmb0-1b_smb1-1b/mmb0-1b_smb1-1b_2p_neigh_3.yaml"
