data:
  batch_size: 2000
  seq_len: 512
  vocab_size: 6033
  num_workers: 0
  pin_mem: true
logging:
  folder: logs/cnd_gtb10_ep300/
  write_tag: jepa
mask:
  n_targets: 4
  n_contexts: 1
  target_mask_size: 10
  context_mask_size: 80

meta:
  copy_data: false
  load_checkpoint: false
  model_name: gt_base
  pred_depth: 2
  pred_emb_dim: 384
  enc_depth : 3
  enc_emb_dim : 384
  read_checkpoint: null
  use_bfloat16: false
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 10
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04
