data:
  batch_size: 10
  data_path: /lustre/scratch126/cellgen/team361/mv10/jepa/nichejepa/scGPT.dataset
  #data_path: /lustre/scratch126/cellgen/team361/mv10/jepa/nichejepa/nichecompass.dataset 
  #data_path: ../../nichejepa-reproducibility/nichejepa-reproducibility/datasets/st_data/gold/cell_neighborhood_tokenizer/sim1_1105fts_10000locs/sim1_1105fts_10000locs_read_depth_shifted_log_2210.dataset
  #data_path: /lustre/scratch126/cellgen/team361/mv10/nichejepa-reproducibility/nichejepa-reproducibility/datasets/st_data/gold/cell_neighborhood_tokenizer/merfish_mouse_brain_subset/merfish_mouse_brain_subset_read_depth_shifted_log_2170.dataset/
  data_set_name: 'scgpt'
  num_workers: 0
  pin_mem: true
  #seq_len: 1461
  #seq_len: 361
  vocab_size: 2781 #this is for scgpt
  #vocab_size: 1107 #this is for simulated data
  #vocab_size: 1087 #this is for merfish data
  just_cell: True
  just_neighborhood: False
  seq_len_cell: 1461 #this is for scgpt
  seq_len_neighborhood: 1461 #this is for scgpt
  has_cls: True
  sample_size: 100000
  sample_subset: False
  random_state: 0
  stratify: False
  split: 0.2
  specific_cell_types: []
  #specific_cell_types: ['Celltype5','Celltype6']
emb:
  weighted_average: False
  average: True
  cls: False
  select_topk: False
  retrieve_gene: False
  retrieve_niche: False
  retrieve_cell: True
  gene_id: 332
  retrieve_position_emb: False
  retrieve_emb_from_layer: 0 # This indicates that we should retrieve embeddings from the layer specified by #retrieve_emb_from_layer and upwards its value should be between zero and #enc_depth-1
logging:
  folder: logs/merfish_200
  write_tag: jepa
mask:
  context_mask_size: 365
  target_mask_size: 14
  n_contexts: 1
  n_targets: 2

meta:
  copy_data: false
  enc_depth: 4
  load_checkpoint: false
  model_name: gt_base
  pred_depth: 4
  pred_emb_dim: 712
  enc_emb_dim: 712
  enc_pred_depth: 44
  read_checkpoint: null
  use_bfloat16: True
optimization:
  ema:
  - 0.3061177254633777
  - 1.0
  learnable: 1
  epochs: 9
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.000001
  start_lr: 5.0e-05
  warmup: 5
  weight_decay: 0.04