data:
  batch_size: 10
  data_path: /lustre/scratch126/cellgen/team361/am84/NicheJEPA/datasets/am84/st_data/gold/cell-neighborhood-tokenizer/sim1_1105genes_100klocs_strongincrements/8-shards/sim1_1105genes_100klocs_strongincrements_4_False_read_depth_shifted_log_2210.dataset
  data_set_name: 'simulated_100k'
  num_workers: 18
  pin_mem: true
  vocab_size: 1107 #this is for simulated_100k
  incl_cell_seq: True
  incl_neighborhood_seq: True
  seq_len_cell: 374 #this is for simulated_100k
  seq_len_neighborhood: 1105 #this is for simulated_100k
  has_cls: True
  sample_size: 5000
  sample_subset: False
  random_state: 0
  stratify: True
  split: 0.2
  specific_cell_types: []
  #specific_cell_types: ['Celltype5','Celltype6']
emb:
  weighted_average: False
  average: True
  cls: False
  select_topk: False
  retrieve_gene: False
  retrieve_niche: False
  retrieve_cell: True
  gene_id: 332
  retrieve_position_emb: False
  retrieve_emb_from_layer: 2 # This indicates that we should retrieve embeddings from the layer specified by #retrieve_emb_from_layer and upwards its value should be between zero and #enc_depth-1
logging:
  folder: logs/simulated_100k
  write_tag: jepa
mask:
  context_mask_size: 1240 # This doesn't have meaning in segment_masking.
  target_mask_size: 10 # This doesn't have meaning in segment_masking.
  n_contexts: 1
  n_targets: 9 # This is equivalent to n_segment in segment_masking.
  per_segment_mask_ratio: 0.2
  segment_masking: True

meta:
  copy_data: false
  enc_depth: 3
  load_checkpoint: false
  model_name: gt_base
  pred_depth: 1
  pred_emb_dim: 768
  enc_emb_dim: 768
  enc_pred_depth: 31
  top_k: 127
  read_checkpoint: null
  use_bfloat16: True
optimization:
  ema:
  - 0.9764319982153814
  - 1.0
  learnable: 1
  epochs: 40
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.000001
  start_lr: 5.0e-05
  warmup: 5
  weight_decay: 0.04

