data:
  dataset_name: 'starmap_merfish_mouse_brain_1_gene_panel'
  raw_data_folder_path: '/lustre/scratch126/cellgen/team361/DATASETS/silver/mmb0-1b_smb1-1b_1p'
  tokenized_data_folder_path: '/lustre/scratch126/cellgen/team361/DATASETS/gold/cell-neighborhood-tokenizer/mmb0-1b_smb1-1b_1p/mmb0-1b_smb1-1b_1p_read_depth_shifted_log_862.dataset/'
  tokenizer_type: 'cell_neighborhood' # 'cell_neighborhood', 'cell_graph'
  random_state: 0
  sample_size: 500
  sample_subset: False
  split: 0.2
  stratify: False
  vocab_size: 1671 # from token dictionary ('/lustre/scratch126/cellgen/team361/DATASETS/tokenizer/cell-neighborhood-tokenizer/mmb0-1b_smb1-1b_1p/token_dictionary.pkl')
  seq_len_cell: 176 # max number of non-zero cell tokens per cell
  seq_len_neighborhood: 309 # max number of non-zero neighborhood tokens per cell
  n_segments: 2 # number of unique segment tokens
  sampling_strategy: null  # null, 'rand_sampling', 'norm_count_rank_sampling', 'rand_sampling_rep', 'norm_count_rank_sampling_rep'
  batch_size: 64
  num_workers: 0
  pin_memory: True
  separate_cls: True
meta:
  gt_type: 'rank' # 'rank', 'counts'
  enc_depth: 3
  enc_emb_dim: 768
  pred_depth: 1
  pred_emb_dim: 768
  special_tokens: ['cls_cell', 'cls_neighborhood']
  #special_tokens: ['cls_cell', 'cls_neighborhood', 'assay', 'species', 'tissue', 'gene_panel', 'batch']
  pos_learnable: False
  seg_learnable: False
  use_bfloat16: True
  use_flash_attention: True
mask:
  n_contexts: 1
  n_targets: 5 # this is the number of blocks in block masking
  block_masking: True # this is used to select block_masking
  context_mask_size: 1220 # this doesn't have meaning in block masking.
  target_mask_size: 10 # this doesn't have meaning in block masking.
  per_block_mask_ratio: 0.5
  controlled_attention_pattern: 
    # Similarly, for the columns, we have the same order, and a 1 indicates attention get masked  between those two parts.
    # 'Matrix', 'null'
    - [0, 1, 0, 1]  # cls_cell
    - [1, 0, 1, 0]  # cls_neighborhood
    - [0, 1, 0, 1]  # cell
    - [1, 0, 1, 0]  # neighborhood
  #controlled_attention_pattern: null
optimization:
  warmup: 1
  epochs: 1
  ema:
  - 0.9764319982153814
  - 1.0
  start_lr: 2.0e-05
  lr: 2.0e-05
  final_lr: 2.0e-05
  weight_decay: 0.04
  final_weight_decay: 0.4
  ipe_scale: 1.0
state:
  log_freq: 20
  checkpoint_freq: 5
  write_tag: nichejepa
  read_timestamp: ''
  load_checkpoint: False # true, false
  read_checkpoint: null # 'jepa-ep5.pth.tar'
