data:
  dataset_name: 'mmb0-1b_smb1-1b_1p'
  raw_data_folder_path: '/lustre/scratch126/cellgen/team361/DATASETS/silver/mmb0-1b_smb1-1b_1p'
  token_dict_folder_path: '/lustre/scratch126/cellgen/team361/DATASETS/tokenizer/cell-graph-tokenizer/mmb0-1b_smb1-1b_1p/token_dictionary.pkl'
  tokenized_data_folder_path: '/lustre/scratch126/cellgen/team361/DATASETS/gold/cell-graph-tokenizer/mmb0-1b_smb1-1b_1p/mmb0-1b_smb1-1b_1p_None_shifted_log_knn_10_1793.dataset'
  tokenizer_type: 'cell_graph' # 'cell_neighborhood', 'cell_graph'
  random_state: 0
  sample_size: 500
  sample_subset: False
  split: 0.2
  stratify: False
  seq_len_cell: 64 # 176 # max number of non-zero cell tokens per cell
  seq_len_neighborhood: 640 # 309 # max number of non-zero neighborhood tokens per cell
  n_segments: 11 # number of unique segment tokens (1 index and 10 neighbor gene segments) # 2
  sampling_strategy: null  # null, 'rand_sampling', 'norm_count_rank_sampling', 'rand_sampling_rep', 'norm_count_rank_sampling_rep'
  batch_size: 32
  num_workers: 6
  pin_memory: True
meta:
  add_cls: True
  gt_type: 'counts' # 'rank', 'counts'
  enc_depth: 3
  enc_emb_dim: 768
  pred_depth: 1
  pred_emb_dim: 768
  special_tokens: ['batch'] # ['batch', 'assay', 'tissue']
  pos_learnable: False
  seg_learnable: False
  use_bfloat16: True
  use_flash_attention: True
mask:
mask:
  n_contexts: 1
  n_targets: 5 # this is the number of blocks in block masking
  block_masking: False # this doesn't have meaning in block masking.
  cell_masking: True # enable cell_masking
  targets_list: null # Here, one can define a list of targets.
  context_mask_size: 200 # this doesn't have meaning in block masking.
  target_mask_size: 50 # this doesn't have meaning in block masking.
  per_block_mask_ratio: 0.5 # [0.5, 0.8]
  #controlled_attention_pattern_enc:
  #  # Similarly, for the columns, we have the same order, and a 1 indicates attention get masked  between those two parts.
  #  # 'Matrix', 'null'
  #  - [0, 1, 0, 1] # cls
  #  - [1, 1, 0, 0] # genes
  #controlled_attention_pattern_pred:
  #  - [0, 1, 0, 1] # cls
  #  - [1, 1, 0, 1] # genes
  #controlled_attention_pattern:
  #  # Similarly, for the columns, we have the same order, and a 1 indicates attention get masked  between those two parts.
  #  # 'Matrix', 'null'
  #  - [0, 0, 0, 1] # cls
  #  - [1, 1, 0, 1] # genes
  controlled_attention_pattern: null
  controlled_attention_type: '' # 'enc' # 'enc', 'pred', 'enc_pred', ''
  restrict_special_attention: True # True, False
optimization:
  warmup: 1
  epochs: 100
  ema:
  - 0.7
  - 1.0
  start_lr: 2.0e-05
  lr: 2.0e-05
  final_lr: 2.0e-05
  weight_decay: 0.04
  final_weight_decay: 0.4
  ipe_scale: 1.0
state:
  log_freq: 20
  checkpoint_freq: 5
  write_tag: nichejepa
  read_timestamp: ''
  load_checkpoint: False # True, False
  read_checkpoint: null # null, 'jepa-ep5.pth.tar'
  checkpoint_freq_iter: 2