# All keys in this YAML file must be in capital letters since
# they will be treated as environmental variables.

job_requirement:
  LSB_DEFAULT_USERGROUP: team361  # The user group to be used for scheduling the job.
  QUEUE: "gpu-lotfollahi"  # The job queue to be used for scheduling the job.
  NUM_NODES: 1  # Number of compute nodes required for the job.
  NUM_GPUS_NODE: 4  # Number of GPUs per node.
  NUM_PROCESSES_NODE: 64  # Number of processes per node.
  MEM_NODE: 256  # Memory allocated per node (in GB).

infiniband:
  NCCL_IB_DISABLE: 1  # 1: Disable InfiniBand, 0: Enable InfiniBand

environment:
  ENV_PATH: "/nfs/users/nfs_s/sb75/.venvs/nemo"  # Path to the environment to be activated.

#artifact:
  ARTIFACT_LOCATION: "/lustre/scratch126/cellgen/team361/sb75/nichejepa-reproducibility/artifacts/mmb0-1b_smb1-1b_2p"  # Path to store the artifacts.
  EXPERIMENT_NAME: "nemo"  # Name of the experiment.
  RUN_NAME: "mmb0-1b_smb1-1b_2p-highema-4"  # Name of the run.

runner_script:
  RUNNER_SCRIPT: "/lustre/scratch126/cellgen/team361/sb75/nichejepa/src/app/runner.sh"  # Path to the runner script.
  TRAINING_SCRIPT_PATH: "/lustre/scratch126/cellgen/team361/sb75/nichejepa/src/app/main_dist.py"  # Path to the training script.
  BACKEND: "nccl"  # Backend for distributed training.
  CONFIG_FILE: "/lustre/scratch126/cellgen/team361/sb75/nichejepa/configs/model/mmb0-1b_smb1-1b_2p.yaml"
